name: mlops-CI

on:
  push:
    branches:
      - kernelridge

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DecisionTree train.py
        run: |
          python train.py | tee dtree_log.txt

      - name: Run KernelRidge train2.py
        run: |
          python train2.py | tee kernelridge_log.txt

      - name: List artifacts
        run: |
          ls -R

      - name: Upload training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            artifacts/
            dtree_log.txt
            kernelridge_log.txt
